Ecommerce_Website_Project/Ecommerce_Website_Project/urls.py
from django.contrib import admin
from django.urls import path
from Ecommerce_Website_Application.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    
    #Admin_Side

    path('admin/', admin.site.urls),

    
    #General_Guest -Register_Users -Logins -Logoutss
        
    path('',about,name="about"),
    path('about/',about,name="about"),
    
    path('register_buyer/',register_buyer,name="register_buyer"),
    path('register_seller/',register_seller,name="register_seller"),
    
    path('login_buyer/',login_buyer,name="login_buyer"),
    path('login_seller/',login_seller,name="login_seller"),
    
    path('logout_buyer/',logout_buyer,name="logout_buyer"),
    path('logout_seller/',logout_seller,name="logout_seller"),
    

    #Buyer_Side **Show** -Products -Sellers -Categories
    
    path('buyer/',buyer,name="buyer"),
    path('buyer/<str:id>',loadproduct,name="loadproduct"),
    
    path('shops/',shops,name="shops"),
    path('shops/<str:id>',loadshop,name="loadshop"),
    
    path('categories/',categories,name="categories"),
    path('categories/<str:id>',loadcategory,name="loadcategory"),


    #Buyer_Side **Cart** **Checkout** **Orders**
    
    path('cart/',cart,name="cart"),
    path('checkout/',checkout,name="checkout"),
    
    path('orders/',orders,name="orders"),


    #Seller_Side **Show** -MyProducts -MyCategories
    
    path('seller/',seller,name="seller"),
    path('seller/<str:id>',loadmyproduct,name="loadmyproduct"),
    
    path('mycategories/',mycategories,name="mycategories"),
    path('mycategories/<str:id>',loadmycategory,name="loadmycategory"),
    

    #Seller_Side **Add** **Manage** -Products

    path('register_product/',register_product,name="register_product"),
    
    path('manageproducts/',manageproducts,name="manageproducts"),
    path('modifyproduct/',modifyproducts,name="modifyproducts"),
    path('deleteproduct/',deleteproducts,name="deleteproducts"),
    
    path('myorders/',myorders,name="myorders"),

    path('reports/',reports,name="reports"),
    path('generate_order_csv/',generate_order_csv,name="generate_order_csv"),
    path('generate_product_csv/',generate_product_csv,name="generate_product_csv"),
    path('generate_order_pdf/',generate_order_pdf,name="generate_order_pdf"),
    path('generate_product_pdf/',generate_product_pdf,name="generate_product_pdf"),
]

urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)

Ecommerce_Website_Project/Ecommerce_Website_Application/models.py
from django.db import models
from django.contrib.auth.models import User

class Contact_Request(models.Model):
    email = models.EmailField(max_length=50)
    purpose = models.TextField(max_length=500)
    def __str__(self):
        return "Contact Request : " + str(self.id)

class Feedback(models.Model):
    email = models.EmailField(max_length=50)
    feedback = models.TextField(max_length=500)
    def __str__(self):
        return "Feedback ID : " + str(self.id)

class Buyer(models.Model):
    New_User = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name= models.CharField(max_length=50)
    email= models.EmailField(max_length=50)
    date = models.DateField()
    gender = models.CharField(max_length=10)
    aadhaar = models.CharField(max_length=12)
    contact = models.CharField(max_length=10)
    address = models.TextField(max_length=400)
    def __str__(self):
        return self.New_User.username

class Seller(models.Model):
    New_User = models.ForeignKey(User, on_delete=models.CASCADE)
    seller_name= models.CharField(max_length=50)
    seller_description= models.CharField(max_length=50)
    logo= models.ImageField(upload_to='Sellers/Logos/')
    banner = models.ImageField(upload_to='Sellers/Banners/')
    gstin = models.CharField(max_length=15)
    email = models.EmailField(max_length=100)
    contact = models.CharField(max_length=10)
    address = models.TextField(max_length=400)
    def __str__(self):
        return self.New_User.username

class Category(models.Model):
    category_name = models.CharField(max_length=50)
    category_description = models.CharField(max_length=100)
    category_icon = models.ImageField(upload_to='Categories/Icons/',default='')
    category_banner = models.ImageField(upload_to='Categories/Banners/',default='')
    def __str__(self):
        return self.category_name
    
class Product(models.Model):
    seller_name = models.ForeignKey(Seller, on_delete=models.CASCADE) 
    product_name = models.CharField(max_length=50)
    product_description = models.CharField(max_length=100)
    product_price = models.IntegerField(default=1)
    product_img = models.ImageField(upload_to='Products/Images')
    status_choice = [
        ('In_Stock','In Stock'),
        ('Out_of_Stock','Out of Stock'),
    ]
    product_status= models.CharField(max_length=50,choices=status_choice,default='In_Stock')
    category_name = models.ForeignKey(Category,on_delete=models.CASCADE)
    def __str__(self):
        return self.product_name
    
class Order(models.Model):

    order_buyer_id = models.ForeignKey(Buyer,on_delete=models.CASCADE)
    order_buyer_first_name = models.CharField(max_length=250)
    order_buyer_last_name = models.CharField(max_length=250)
    order_buyer_email = models.CharField(max_length=250)
    order_buyer_contact = models.CharField(max_length=250)
    order_buyer_address = models.CharField(max_length=250)

    order_seller_id = models.ForeignKey(Seller,on_delete=models.CASCADE)
    order_seller_name = models.CharField(max_length=250)
    order_seller_email = models.CharField(max_length=250)
    order_seller_contact = models.CharField(max_length=250)
    order_seller_address = models.CharField(max_length=250)

    order_product_id = models.ForeignKey(Product,on_delete=models.CASCADE)
    order_product_name = models.CharField(max_length=250)
    order_product_price = models.CharField(max_length=250)
    order_quantity= models.IntegerField()
    order_total= models.IntegerField()

    buyer_status = models.BooleanField(default=False)
    seller_status = models.BooleanField(default=False)

    status_choice = [
        ('Order_Placed','Ordered Placed'),
        ('Cancelled','Cancelled'),
        ('Accepted','Accepted'),
        ('Rejected','Rejected'),
        ('Out_For_Pickup','Out For Pickup'),
        ('Picked_Up','Picked Up'),
        ('Out_For_Delivery','Out For Delivery'),
        ('Delivered','Delivered'),
    ]
    order_status= models.CharField(max_length=50,choices=status_choice,default='Order_Placed')

    def __str__(self):
        return "Order Id : " + str(self.id)

Ecommerce_Website_Project/Ecommerce_Website_Application/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate , login , logout
from django.http import HttpResponse, FileResponse
from .models import *
from django.contrib import messages
import csv
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

# Create your views here.
def generate_order_pdf(request):
    buf = io.BytesIO()
    c = canvas.Canvas(buf,pagesize=letter,bottomup=0)
    textob=c.beginText()
    textob.setTextOrigin(inch,inch)
    textob.setFont("Helvetica",16)
    seller_id = request.session.get('seller_id')
    accepted_orders=Order.objects.filter(order_seller_id=seller_id,order_status='Accepted')
    lines = []
    lines.append("All Accepted Orders Report")
    lines.append(" ")
    count=1
    for each in accepted_orders:
        lines.append(str(count))
        lines.append("Buyer Name : "+each.order_buyer_first_name+' '+each.order_buyer_last_name)
        lines.append("Buyer Email : "+each.order_buyer_email)
        lines.append("Buyer Contact : "+str(each.order_buyer_contact))
        lines.append("Buyer Address : ")
        lines.append(each.order_buyer_address)
        lines.append("Product Name : " +each.order_product_name)
        lines.append("Product Price : "+str(each.order_product_price))
        lines.append("Order Quantity : "+str(each.order_quantity))
        lines.append("Order Total : "+str(each.order_total))
        lines.append(" ")
        count+=1
    count=0
    for each in lines:
        textob.textLine(str(each))
        count+=1
    c.drawText(textob)
    c.showPage()
    c.save()
    buf.seek(0)
    return FileResponse(buf,as_attachment=True,filename='Generated_Orders_Report.pdf')

def generate_product_pdf(request):
    buf = io.BytesIO()
    c = canvas.Canvas(buf,pagesize=letter,bottomup=0)
    textob=c.beginText()
    textob.setTextOrigin(inch,inch)
    textob.setFont("Helvetica",16)
    seller_id = request.session.get('seller_id')
    Out_Stock=Product.objects.filter(seller_name=seller_id,product_status='Out_of_Stock')
    lines = []
    count=1
    lines.append("All Out of Products Report")
    lines.append(" ")
    for each in Out_Stock:
        lines.append(str(count))
        lines.append("Product Name : "+str(each.product_name))
        lines.append("Product Price : "+str(each.product_price))
        lines.append("Product Description : "+str(each.product_description))
        lines.append(" ")
        count+=1
    count=0
    for each in lines:
        textob.textLine(str(each))
        count+=1
    c.drawText(textob)
    c.showPage()
    c.save()
    buf.seek(0)
    return FileResponse(buf,as_attachment=True,filename='Generated_Products_Report.pdf')

def about(request):
    if request.method == "POST":
        email=request.POST['email']
        content=request.POST['content']
        type=request.POST['type']
        if type == "contact":
            new_contact_req = Contact_Request(email=email,purpose=content)
            new_contact_req.save()
        elif type == "feedback":
            new_feedback = Feedback(email=email,feedback=content)
            new_feedback.save()
        return redirect('/about/')
    else:
        return render(request,'about.html')

def register_buyer(request):
    
    if request.method=="POST":
        
        username=request.POST['create_username']
        create_password=request.POST['create_password']
        confirm_password=request.POST['confirm_password']
        type="BUYER"
        
        first_name=request.POST['first_name']
        last_name=request.POST['last_name']
        email=request.POST['email']
        gender=request.POST['gender']
        date=request.POST['date']
        aadhaar=request.POST['aadhaar']
        contact=request.POST['contact']
        address=request.POST['address']

        if create_password == confirm_password:
            
            New_User = User.objects.create_user(username=username,password=confirm_password)
            New_User.first_name = type
            New_User.save()
            
            New_Buyer = Buyer(New_User=New_User,first_name=first_name,last_name=last_name,email=email,gender=gender,date=date,aadhaar=aadhaar,contact=contact,address=address)
            New_Buyer.save()    
        
        return redirect('/login_buyer/')
    
    else: 
        return render(request,'register_buyer.html')

def register_seller(request):
    
    if request.method=="POST":
        
        username=request.POST['create_username']
        create_password=request.POST['create_password']
        confirm_password=request.POST['confirm_password']
        type="SELLER"
        
        seller_name=request.POST['seller_name']
        seller_description=request.POST['seller_description']
        logo=request.FILES['logo']
        banner=request.FILES['banner']
        gstin=request.POST['gstin']
        email=request.POST['email']
        contact=request.POST['contact']
        address=request.POST['address']

        if create_password == confirm_password:
            
            New_User = User.objects.create_user(username=username,password=confirm_password)
            New_User.first_name=type
            New_User.save()
            
            New_Seller = Seller(New_User=New_User,seller_name=seller_name,seller_description=seller_description,logo=logo,banner=banner,gstin=gstin,email=email,contact=contact,address=address)
            New_Seller.save()
        
        return redirect('/login_seller/')
    
    else:
        
        return render(request,'register_seller.html')

def login_buyer(request):
    
    if request.method=="POST":
        
        username=request.POST['username']
        password=request.POST['password']
        
        is_buyer = User.objects.get(username=username)
        
        buyer_id = Buyer.objects.get(New_User=is_buyer)

        if is_buyer.first_name == "BUYER":
            
            buyer = authenticate(username=username,password=password)
            
            if buyer:    
                
                login(request,buyer) 
                request.session['type'] = is_buyer.first_name
                request.session['buyer_id']=buyer_id.id
                request.session['buyer_username']=is_buyer.username
                return redirect('/buyer/')
            
            else:
                
                return redirect('/login_buyer/')
        else:
            
            return redirect('/login_buyer/')      
    else:
        
        return render(request,'login_buyer.html')

def login_seller(request):
    
    if request.method=="POST":
        
        username=request.POST['username']
        password=request.POST['password']
        
        is_seller = User.objects.get(username=username)
        seller_id = Seller.objects.get(New_User=is_seller)
        if is_seller.first_name == "SELLER":
            
            seller = authenticate(username=username,password=password)
            
            if seller:    
                
                login(request,seller)  
                request.session['type'] = is_seller.first_name
                request.session['seller_id']=seller_id.id
                request.session['seller_username']=is_seller.username
                return redirect('/seller/')
            
            else:
                
                return redirect('/login_seller/')
        else:
            
            return redirect('/login_seller/') 
    else:
        
        return render(request,'login_seller.html')

def buyer(request):

        if request.method == "GET":
            Product_Data = Product.objects.filter(product_status="In_Stock")
            
            context= {
                'Product_Data' : Product_Data
            }
            cart=request.session.get('cart')
            if not cart:
                request.session['cart'] = {}
            return render(request,'buyer.html',context=context)
        
        elif request.method == "POST":
            
            products = request.POST['Product']
            remove = request.POST.get('remove')
            cart = request.session.get('cart')
            if cart:
                quantity = cart.get(products)
                if quantity:
                    if remove:
                        if quantity<=1:
                            cart.pop(products)
                        else:
                            cart[products] = quantity-1
                    else:
                        cart[products] = quantity+1
                else:
                    cart[products] = 1
            else:
                cart = {}
                cart[products] = 1 
            
            request.session['cart'] = cart
            return redirect('/buyer/')

def shops(request):
    Sellers_Data = Seller.objects.all()
    
    context= {
        'Sellers_Data' : Sellers_Data
    }
    
    return render(request,'shops.html',context=context)

def categories(request):
    Categories_Data = Category.objects.all()

    context= {
        'Categories_Data':Categories_Data
    }

    return render(request,'categories.html',context=context)

def logout_buyer(request):
    logout(request)
    return redirect('/')

def logout_seller(request):
    logout(request)
    return redirect('/')

def seller(request):
    id = request.session.get('seller_id')
    Sellers_Data = Seller.objects.get(id=id)
    Product_Data = Product.objects.filter(seller_name=id,product_status="In_Stock")
    context = {
        'Sellers_Data':Sellers_Data,
        'Product_Data':Product_Data,
    }
    return render(request,'seller.html',context = context)

def register_product(request):
    if request.method=="POST":
        product_seller = request.POST['seller_name']
        product_name = request.POST['product_name']
        product_description = request.POST['product_description']

Ecommerce_Website_Project/Ecommerce_Website_Application/templates/buyer.html
{% extends "buyer_base.html" %}
{% block content %}
{%load static%}
{%load cart%}
    <h1>All Products</h1>
    <div class="product-card-container">
        {% for Product in Product_Data %}
            <div class="product-card" id={{ Product.id }}>
                <img src="{{ Product.product_img.url}}" alt="Image" width="250"><hr>
                <h3>{{ Product.product_name }}</h3><hr>
                <h3>Price : Rs. {{ Product.product_price }}</h3>
                <a href="/buyer/{{ Product.id }}"><button>View Product</button></a>
            
                <div class="card-footer">
                    {% if Product|is_in_cart:request.session.cart %}
                        <form action="/buyer/#{{Product.id}}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name='Product' value="{{ Product.id }}"></input>
                            <input hidden type="number" name='remove' value='-1'></input>
                            <input type="submit" value=" - " class="col-2 btn btn-block btn-secondary"></input>    
                        </form>                
                        <div class="text-center col">{{Product|cart_quantity:request.session.cart}} In Cart</div>
                        <form action="/buyer/#{{Product.id}}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name='Product' value="{{ Product.id }}"></input>
                            <input type="submit" value=" + " class="col-2 btn btn-block btn-secondary"></input>    
                        </form>
                    
                    {% else %}
                    <form action="/buyer/#{{Product.id}}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name='Product' value="{{ Product.id }}"></input>
                        <input type="submit" value="Add To Cart"></input>
                    </form> 
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

Ecommerce_Website_Project/Ecommerce_Website_Application/templates/buyer_base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buyer</title>
    <link rel="stylesheet" href="{% static 'registration_forms.css' %}">
    <link rel ="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
</head>
<body class="buyer_body">
    {% if user.is_authenticated and request.session.type == 'BUYER' %}
    <nav class="navbar">
        <div class="logo">INDEV</div>
        <ul class="nav-links">
            <li><a href="/buyer/">All Products</a></li>
            <li><a href="/shops/">All Shops</a></li>
            <li><a href="/categories/">All Categories</a></li>
            <li><a href="/cart/">My Cart</a></li>
            <li><a href="/orders/">My Order</a></li>
        </ul>
        <div class="logout">
            <a href="/logout_buyer/"><button type="button" class="logout" >Logout</button></a>
        </div>
    </nav>
    
    {% block content %}
        
    {% endblock %}

    {% else %}
    <h1>Attempted Unauthorized Access Faliure</h1>
    {% endif %}
    
</body>
<footer class="site-footer">
    &copy; 2025 All rights reserved.
</footer>
</html>

Ecommerce_Website_Project/Ecommerce_Website_Application/templates/cart.html
{% extends "buyer_base.html" %}
{% block content %}
{%load static%}
{%load cart%}

<h1>My Cart</h1>
<div class="container">
<table class="Cart-Table">
    <thead>
        <tr>
            <th>Sno.</th>
            <th>Product Image</th>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {% for Product in cart_Data %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td><img src="{{ Product.product_img.url}}" alt="Image" width="100" height="100"></td>
            <td>{{ Product.product_name }}</td>
            <td>{{ Product.product_price }}</td>
            <td>{{ Product|cart_quantity:request.session.cart }}</td>
            <td>{{ Product|price_total:request.session.cart }}</td>
        </tr>
        {% endfor %}
        <tfoot>
            <th colspan="2">Grand Total</th>
            <th colspan="2">{{ cart_Data|grand_price_total:request.session.cart }}</th>
            <th colspan="2" class="checkout">
                <a href="/checkout/"><button type="button" class="checkout" >Check Out</button></a>
            </th>
        </tfoot>
    </tbody>
</table>
</div>
{% endblock %}

Ecommerce_Website_Project/Ecommerce_Website_Application/templates/categories.html
{% extends "buyer_base.html" %}
{% block content %}
{%load static%}
{%load cart%}
    <h1>All Categories</h1>
    <div class="shop-card-container">
        {% for Category in Categories_Data %}
        <div class="shop-card">
            <img src="{{ Category.category_icon.url}}" alt="Image" width="250">
            <div class="text">
                <h2>{{ Category.category_name }}</h2>
                <hr>
                <h3>{{ Category.category_description }}</h3>
                
                <a href="/categories/{{ Category.id }}"><button>View Category</button></a>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}
   

Ecommerce_Website_Project/Ecommerce_Website_Application/templates/guest_base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Guest</title>
    <link rel="stylesheet" href="{% static 'registration_forms.css' %}">
    <link rel ="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <script src="{% static 'script.js' %}"></script>
</head>
<body class="guest_body">
        <nav class="navbar">
        <div class="logo">INDEV</div>
        <ul class="nav-links">
            <li><a href="/about/">About Us</a></li>
            <li><a href="/login_buyer/">Login As Buyer</a></li>
            <li><a href="/login_seller/">Login As Seller</a></li>
            <li><a href="/register_buyer/">Register As Buyer</a></li>
            <li><a href="/register_seller/">Register As Seller</a></li>
        </ul>
        </nav>
        {% block content %}
        
        {% endblock %}
</body>
<footer class="site-footer">
    &copy; 2025 All rights reserved.
</footer>
</html>

Ecommerce_Website_Project/Ecommerce_Website_Application/templates/homepage.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Navigation Bar with Dropdown</title>
    <link rel="stylesheet" href="{% static 'registration_forms.css' %}">
</head>
<body>

    <nav class="navbar">
        <div class="logo">MyLogo</div>
        <ul class="nav-links">
            <li><a href="#">Products</a></li>
            <li><a href="#">Shops</a></li>
            <li><a href="#">About Us</a></li>
            <li><a href="#">My Cart</a></li>
        </ul>
        <div class="dropdown">
            <button class="dropbtn">Login/Register</button>
            <div class="dropdown-content">
                <a href="login_buyer/">Login as Buyer</a>
                <a href="login_seller/">Login as Seller</a>
                <a href="register_buyer/">Register as Buyer</a>
                <a href="register_seller/">Register as Seller</a>
            </div>
        </div>
    </nav>

</body>
</html>

Ecommerce_Website_Project/Ecommerce_Website_Application/templates/loadcategory.html
{% extends "buyer_base.html" %}
{% block content %}
{%load static%}
{%load cart%}
    <div class="shop-card-container">
        {% for category in Category_Data %}
        <img src="{{ category.category_banner.url}}" alt="Image" width="1250">
        <div class="shop-card">
            <img src="{{ category.category_icon.url}}" alt="Image" width="250">
            <div class="text">
                <hr>
                <h1>{{ category.category_name }}</h1>
                <hr>
                <h2>{{ category.category_description }}</h2>
            </div>
        </div>
        
    </div>
    <h1>Our Products</h1>
    <div class="product-card-container">
        {% for Product in Product_Data %}
            <div class="product-card" id={{Product.id}}>
                <img src="{{ Product.product_img.url}}" alt="Image" width="250"><hr>
                <h3>{{ Product.product_name }}</h3><hr>
                <h3>Price : Rs. {{ Product.product_price }}</h3>
                <a href="/buyer/{{ Product.id }}"><button>View Product</button></a>
            
                <div class="card-footer">
                    {% if Product|is_in_cart:request.session.cart %}
                        <form action="/categories/{{category.id}}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name='Product' value="{{ Product.id }}"></input>
                            <input hidden type="number" name='remove' value='-1'></input>
                            <input type="submit" value=" - " class="col-2 btn btn-block btn-secondary"></input>    
                        </form>                
                        <div class="text-center col">{{Product|cart_quantity:request.session.cart}} In Cart</div>
                        <form action="/categories/{{category.id}}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name='Product' value="{{ Product.id }}"></input>
                            <input type="submit" value=" + " class="col-2 btn btn-block btn-secondary"></input>    
                        </form>
                    
                    {% else %}
                    <form action="/categories/{{category.id}}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name='Product' value="{{ Product.id }}"></input>
                        <input type="submit" value="Add To Cart"></input>
                    </form> 
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        {% endfor %}
        {% endblock %}

Ecommerce_Website_Project/Ecommerce_Website_Application/templates/login_seller.html
{% extends "guest_base.html" %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="card">
            <h2>Seller Login</h2>
            <form action='/login_seller/' method="post">
                {% csrf_token %} 
                <table>
                    <tr><td>Username:</td><td><input type="text" name="username" required></input></td></tr>
                    <tr><td>Password:</td><td><input type="password" name="password" required></input></td></tr>
                    <tr><td colspan="2"><button type="submit">Login</button></td></tr>
                </table>   
            </form>
        </div>
    </div>
{% endblock %}

Ecommerce_Website_Project/Ecommerce_Website_Application/templates/mycategories.html
{% extends "seller_base.html" %}
{% block content %}
{%load static%}
{%load cart%}
    <h1>My Categories</h1>
    <div class="shop-card-container">
        {% for Category in Categories_Data %}
        <div class="shop-card">
            <img src="{{ Category.category_icon.url}}" alt="Image" width="250">
            <div class="text">
                <h2>{{ Category.category_name }}</h2>
                <hr>
                <h3>{{ Category.category_description }}</h3>
                
                <a href="/mycategories/{{ Category.id }}"><button>View Shop</button></a>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

Ecommerce_Website_Project/Ecommerce_Website_Application/templates/orders.html
{% extends "buyer_base.html" %}
{% block content %}
{%load static%}
    <h1>My Orders</h1>
    <div class="order-card-container">
        {% for Order in Orders_Data %}
            <div class="order-card" id={{ Order.id }}>
                <h3>Order Number : {{Order.id}}</h3>
                <hr>
                <h4>Buyer Details</h4>
                <hr>
                <h5>Username : {{Order.order_buyer_id}}</h5>
                <h5>Name : {{Order.order_buyer_first_name}} {{Order.order_buyer_last_name}}</h5>
                <h5>Email : {{Order.order_buyer_email}}</h5>
                <h5>Contact : {{Order.order_buyer_contact}}</h5>
                <h5>Address : {{Order.order_buyer_address}}</h5>
                <hr>
                <h4>Order Details</h4>
                <hr>
                <h5>Name : {{Order.order_product_name}}</h5>
                <h5>Price : {{Order.order_product_price}}</h5>
                <h5>Quantity : {{Order.order_quantity}}</h5>
                <h5>Total : {{Order.order_total}}</h5>
                <h5>Status : {{Order.get_order_status_display}}</h5>
                {%if Order.order_status == 'Order_Placed' %}
                    <form action="/orders/" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name='Order_id' value="{{ Order.id }}"></input>
                    <input type="hidden" name ='Set' value="Cancelled"></input>
                    <td><button class="red" type="submit">Cancel</button></td>
                    </form> 
                
                {%elif Order.order_status == 'Cancelled' or Order.order_status == 'Delivered' or Order.order_status == 'Rejected' %}
                    <form action="/orders/" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name='Order_id' value="{{ Order.id }}"></input>
                    <input type="hidden" name ='Set' value="Delete"></input>
                    <td><button class="red" type="submit">Delete</button></td>
                    </form> 
                {%endif%}
            </div>
        {% endfor %}
    </div>
{% endblock %}

Ecommerce_Website_Project/Ecommerce_Website_Application/templates/shops.html
{% extends "buyer_base.html" %}
{% block content %}
{%load static%}
{%load cart%}
    <h1> All Shops</h1>
    <div class="shop-card-container">
        {% for Seller in Sellers_Data %}
        <div class="shop-card">
            <img src="{{ Seller.logo.url}}" alt="Image" width="250">
            <div class="text">
                <h2>{{ Seller.seller_name }}</h2>
                <hr>
                <h3>{{ Seller.seller_description }}</h3>
                
                <a href="/shops/{{ Seller.id }}"><button>View Shop</button></a>
            </div>
        </div>
    
        {% endfor %}
    </div>
        {% endblock %}